// Placeholder examples shown inside input boxes, tailored per industry and interface language.
// Fields: topic, notes, campaign, objective, tags, voice, cta.

export const EXAMPLES = {
  travel: {
    ar: {
      topic: 'خمسة أنشطة عائلية في لنكاوي',
      notes: 'ركّز على الأنشطة المناسبة للأطفال وأفضل وقت للزيارة',
      campaign: 'عروض صيف 2027',
      objective: 'زيادة حجوزات الباقات العائلية بنسبة 20٪ خلال الصيف',
      tags: 'لنكاوي، شاطئ، عائلة',
      voice: 'دافئ وموثوق وعملي — كصديق خبير بالسفر',
      cta: 'احجز رحلتك الآن عبر واتساب',
    },
    en: {
      topic: '5 family activities in Langkawi',
      notes: 'Mention kid-friendly spots and the best months to visit',
      campaign: 'Summer getaways 2027',
      objective: 'Grow family package bookings by 20% this summer',
      tags: 'langkawi, beach, family',
      voice: 'Warm, trustworthy and practical — like an expert friend',
      cta: 'Book your trip on WhatsApp today',
    },
    ms: {
      topic: '5 aktiviti keluarga di Cameron Highlands',
      notes: 'Sebut tempat mesra kanak-kanak dan bulan terbaik untuk melawat',
      campaign: 'Cuti sekolah 2027',
      objective: 'Tingkatkan tempahan pakej keluarga sebanyak 20% musim cuti ini',
      tags: 'cameron highlands, ladang teh, keluarga',
      voice: 'Mesra, dipercayai dan praktikal — seperti kawan yang arif',
      cta: 'Tempah percutian anda sekarang',
    },
    fr: {
      topic: '5 activités en famille à Penang',
      notes: 'Citer les lieux adaptés aux enfants et la meilleure saison',
      campaign: 'Escapades d’été 2027',
      objective: 'Augmenter de 20 % les réservations familiales cet été',
      tags: 'penang, plage, famille',
      voice: 'Chaleureux, fiable et pratique — comme un ami expert',
      cta: 'Réservez votre voyage dès aujourd’hui',
    },
  },

  news: {
    ar: {
      topic: 'ما الذي يعنيه قرار رفع الفائدة لميزانية أسرتك؟',
      notes: 'اشرح الأرقام ببساطة وأضف رأي خبير اقتصادي محلي',
      campaign: 'تغطية الانتخابات 2027',
      objective: 'رفع عدد المشتركين في النشرة اليومية إلى 10 آلاف',
      tags: 'اقتصاد، مؤتمر صحفي، مدينة',
      voice: 'دقيق ومحايد وواضح — يحترم وقت القارئ',
      cta: 'تابع التغطية الكاملة على موقعنا',
    },
    en: {
      topic: 'What the new interest rate means for your budget',
      notes: 'Explain the numbers simply and quote a local economist',
      campaign: 'Election coverage 2027',
      objective: 'Reach 10,000 subscribers to the daily newsletter',
      tags: 'economy, press conference, city',
      voice: 'Accurate, neutral and clear — respects the reader’s time',
      cta: 'Read the full story on our site',
    },
    ms: {
      topic: 'Apa maksud kenaikan OPR kepada bajet isi rumah',
      notes: 'Terangkan angka dengan mudah dan petik pendapat ahli ekonomi',
      campaign: 'Liputan PRN 2027',
      objective: 'Capai 10,000 pelanggan buletin harian',
      tags: 'ekonomi, sidang media, bandar',
      voice: 'Tepat, berkecuali dan jelas — menghormati masa pembaca',
      cta: 'Baca laporan penuh di laman kami',
    },
    fr: {
      topic: 'Hausse des taux : quel impact sur votre budget ?',
      notes: 'Expliquer les chiffres simplement et citer un économiste local',
      campaign: 'Couverture des élections 2027',
      objective: 'Atteindre 10 000 abonnés à la newsletter quotidienne',
      tags: 'économie, conférence de presse, ville',
      voice: 'Précis, neutre et clair — respecte le temps du lecteur',
      cta: 'Lisez l’article complet sur notre site',
    },
  },

  tech: {
    ar: {
      topic: 'ثلاث طرق لأتمتة فواتيرك وتوفير 5 ساعات أسبوعيًا',
      notes: 'استخدم مثالًا من شركة صغيرة وتجنّب المصطلحات المعقدة',
      campaign: 'إطلاق الإصدار 3.0',
      objective: 'الحصول على 500 تسجيل للنسخة التجريبية خلال شهر',
      tags: 'لوحة تحكم، فريق، حاسوب محمول',
      voice: 'ذكي وبسيط ومباشر — يشرح التقنية بلغة الناس',
      cta: 'جرّب النسخة المجانية اليوم',
    },
    en: {
      topic: '3 ways to automate invoicing and save 5 hours a week',
      notes: 'Use a small-business example and skip the jargon',
      campaign: 'Version 3.0 launch',
      objective: 'Get 500 free-trial sign-ups within one month',
      tags: 'dashboard, team, laptop',
      voice: 'Smart, simple and direct — tech explained in plain words',
      cta: 'Start your free trial',
    },
    ms: {
      topic: '3 cara automasikan invois dan jimat 5 jam seminggu',
      notes: 'Guna contoh perniagaan kecil dan elakkan istilah teknikal',
      campaign: 'Pelancaran versi 3.0',
      objective: 'Dapatkan 500 pendaftaran percubaan percuma dalam sebulan',
      tags: 'papan pemuka, pasukan, komputer riba',
      voice: 'Bijak, ringkas dan terus — teknologi dalam bahasa mudah',
      cta: 'Cuba versi percuma sekarang',
    },
    fr: {
      topic: '3 façons d’automatiser vos factures',
      notes: 'Prendre l’exemple d’une PME et éviter le jargon technique',
      campaign: 'Lancement de la version 3.0',
      objective: 'Obtenir 500 inscriptions à l’essai gratuit en un mois',
      tags: 'tableau de bord, équipe, ordinateur portable',
      voice: 'Malin, simple et direct — la tech expliquée sans jargon',
      cta: 'Commencez votre essai gratuit',
    },
  },

  restaurants: {
    ar: {
      topic: 'قصة طبق المندي الذي يطلبه زبائننا كل جمعة',
      notes: 'اذكر المكونات الطازجة وطريقة الطهي التقليدية في الفرن',
      campaign: 'قائمة رمضان 2027',
      objective: 'زيادة حجوزات الإفطار الجماعي بنسبة 30٪',
      tags: 'مندي، مطبخ، طاولة عائلية',
      voice: 'دافئ وشهي وكريم — كضيافة البيت',
      cta: 'احجز طاولتك الآن',
    },
    en: {
      topic: 'The story behind our Friday mandi',
      notes: 'Highlight fresh ingredients and the slow underground oven',
      campaign: 'Ramadan menu 2027',
      objective: 'Increase group iftar reservations by 30%',
      tags: 'mandi, kitchen, family table',
      voice: 'Warm, appetising and generous — like home hospitality',
      cta: 'Reserve your table now',
    },
    ms: {
      topic: 'Rahsia nasi lemak kukus kegemaran pelanggan kami',
      notes: 'Tonjolkan sambal buatan sendiri dan bahan segar setiap pagi',
      campaign: 'Menu Ramadan 2027',
      objective: 'Tingkatkan tempahan berbuka puasa berkumpulan sebanyak 30%',
      tags: 'nasi lemak, dapur, meja keluarga',
      voice: 'Mesra, menyelerakan dan murah hati — macam makan di rumah',
      cta: 'Tempah meja anda sekarang',
    },
    fr: {
      topic: 'L’histoire de notre tajine du vendredi',
      notes: 'Mettre en avant les produits frais et la cuisson lente',
      campaign: 'Menu du Ramadan 2027',
      objective: 'Augmenter de 30 % les réservations d’iftar en groupe',
      tags: 'tajine, cuisine, table familiale',
      voice: 'Chaleureux, gourmand et généreux — comme à la maison',
      cta: 'Réservez votre table',
    },
  },

  education: {
    ar: {
      topic: 'كيف تساعد طفلك على المذاكرة دون ضغط',
      notes: 'قدّم نصائح عملية للأهل مع جدول يومي بسيط',
      campaign: 'العودة إلى المدرسة 2027',
      objective: 'تسجيل 200 طالب جديد قبل بداية الفصل الدراسي',
      tags: 'فصل دراسي، طلاب، مكتبة',
      voice: 'مشجّع وواضح وصبور — كمعلم يهتم بكل طالب',
      cta: 'سجّل ابنك الآن',
    },
    en: {
      topic: 'How to help your child study without stress',
      notes: 'Give parents practical tips and a simple daily routine',
      campaign: 'Back to school 2027',
      objective: 'Enrol 200 new students before the term starts',
      tags: 'classroom, students, library',
      voice: 'Encouraging, clear and patient — a teacher who cares',
      cta: 'Enrol your child today',
    },
    ms: {
      topic: 'Cara bantu anak mengulang kaji tanpa tekanan',
      notes: 'Beri tip praktikal kepada ibu bapa dan jadual harian ringkas',
      campaign: 'Kembali ke sekolah 2027',
      objective: 'Daftar 200 pelajar baharu sebelum sesi persekolahan bermula',
      tags: 'bilik darjah, pelajar, perpustakaan',
      voice: 'Memberi semangat, jelas dan sabar — guru yang prihatin',
      cta: 'Daftarkan anak anda sekarang',
    },
    fr: {
      topic: 'Aider votre enfant à réviser sans stress',
      notes: 'Donner des conseils concrets aux parents et une routine simple',
      campaign: 'Rentrée scolaire 2027',
      objective: 'Inscrire 200 nouveaux élèves avant la rentrée',
      tags: 'salle de classe, élèves, bibliothèque',
      voice: 'Encourageant, clair et patient — un enseignant attentif',
      cta: 'Inscrivez votre enfant',
    },
  },

  training: {
    ar: {
      topic: 'خمس مهارات قيادية يطلبها أصحاب العمل في 2027',
      notes: 'اربط كل مهارة بمثال من بيئة العمل وأشر إلى الشهادة المعتمدة',
      campaign: 'دبلوم القيادة – دفعة أكتوبر',
      objective: 'ملء 40 مقعدًا في الدفعة القادمة خلال ستة أسابيع',
      tags: 'ورشة عمل، مدرب، شهادة',
      voice: 'مهني وملهم وعملي — يركز على النتائج في العمل',
      cta: 'احجز مقعدك في الدورة',
    },
    en: {
      topic: '5 leadership skills employers want in 2027',
      notes: 'Tie each skill to a workplace example and mention accreditation',
      campaign: 'Leadership diploma – October intake',
      objective: 'Fill 40 seats in the next cohort within six weeks',
      tags: 'workshop, trainer, certificate',
      voice: 'Professional, inspiring and practical — focused on results',
      cta: 'Secure your seat today',
    },
    ms: {
      topic: '5 kemahiran kepimpinan yang dicari majikan pada 2027',
      notes: 'Kaitkan setiap kemahiran dengan contoh di tempat kerja',
      campaign: 'Diploma kepimpinan – ambilan Oktober',
      objective: 'Isi 40 tempat dalam kumpulan seterusnya dalam enam minggu',
      tags: 'bengkel, jurulatih, sijil',
      voice: 'Profesional, memberi inspirasi dan praktikal',
      cta: 'Daftar tempat anda sekarang',
    },
    fr: {
      topic: '5 compétences de leadership recherchées en 2027',
      notes: 'Illustrer chaque compétence par un cas concret en entreprise',
      campaign: 'Diplôme leadership – session d’octobre',
      objective: 'Remplir 40 places de la prochaine session en six semaines',
      tags: 'atelier, formateur, certificat',
      voice: 'Professionnel, inspirant et concret — orienté résultats',
      cta: 'Réservez votre place',
    },
  },

  nonprofit: {
    ar: {
      topic: 'كيف وصل تبرعك إلى 300 أسرة هذا الشتاء',
      notes: 'شارك قصة أسرة واحدة بإذنها وأرقامًا واضحة عن التوزيع',
      campaign: 'حملة دفء الشتاء 2027',
      objective: 'جمع تبرعات لتوفير 500 سلة غذائية قبل نهاية ديسمبر',
      tags: 'متطوعون، توزيع، أطفال',
      voice: 'صادق ومتعاطف وشفاف — يحترم كرامة المستفيدين',
      cta: 'تبرّع الآن وكن جزءًا من الأثر',
    },
    en: {
      topic: 'How your donation reached 300 families this winter',
      notes: 'Share one family’s story (with consent) and clear numbers',
      campaign: 'Winter warmth appeal 2027',
      objective: 'Raise enough to deliver 500 food baskets by December',
      tags: 'volunteers, distribution, children',
      voice: 'Honest, compassionate and transparent — dignity first',
      cta: 'Donate now and make an impact',
    },
    ms: {
      topic: 'Bagaimana sumbangan anda sampai kepada 300 keluarga',
      notes: 'Kongsi kisah satu keluarga (dengan izin) dan angka yang jelas',
      campaign: 'Tabung bantuan banjir 2027',
      objective: 'Kumpul dana untuk 500 bakul makanan sebelum Disember',
      tags: 'sukarelawan, agihan, kanak-kanak',
      voice: 'Ikhlas, prihatin dan telus — menjaga maruah penerima',
      cta: 'Derma sekarang',
    },
    fr: {
      topic: 'Comment votre don a aidé 300 familles cet hiver',
      notes: 'Partager l’histoire d’une famille (avec accord) et des chiffres',
      campaign: 'Appel solidarité hiver 2027',
      objective: 'Financer 500 paniers alimentaires d’ici décembre',
      tags: 'bénévoles, distribution, enfants',
      voice: 'Sincère, bienveillant et transparent — la dignité avant tout',
      cta: 'Faites un don maintenant',
    },
  },

  ecommerce: {
    ar: {
      topic: 'كيف تختار حقيبة السفر المناسبة لرحلتك القادمة',
      notes: 'قارن بين المقاسات واذكر الشحن المجاني للطلبات فوق 200 رنجت',
      campaign: 'تخفيضات 11.11',
      objective: 'رفع معدل التحويل في المتجر إلى 3٪ خلال أسبوع العروض',
      tags: 'منتج، تغليف، توصيل',
      voice: 'ودود وسريع ومقنع — كبائع يعرف ما تحتاجه',
      cta: 'تسوّق الآن قبل نفاد الكمية',
    },
    en: {
      topic: 'How to pick the right suitcase for your next trip',
      notes: 'Compare sizes and mention free shipping over RM200',
      campaign: '11.11 mega sale',
      objective: 'Lift store conversion rate to 3% during sale week',
      tags: 'product, packaging, delivery',
      voice: 'Friendly, quick and persuasive — a seller who gets you',
      cta: 'Shop now before it sells out',
    },
    ms: {
      topic: 'Cara pilih bagasi yang sesuai untuk percutian anda',
      notes: 'Bandingkan saiz dan sebut penghantaran percuma melebihi RM200',
      campaign: 'Jualan mega 11.11',
      objective: 'Naikkan kadar penukaran kedai kepada 3% sepanjang minggu jualan',
      tags: 'produk, bungkusan, penghantaran',
      voice: 'Mesra, pantas dan meyakinkan — penjual yang faham anda',
      cta: 'Beli sekarang sebelum habis',
    },
    fr: {
      topic: 'Bien choisir sa valise pour votre prochain voyage',
      notes: 'Comparer les tailles et mentionner la livraison offerte dès 50 €',
      campaign: 'Soldes du Black Friday',
      objective: 'Porter le taux de conversion à 3 % pendant la semaine promo',
      tags: 'produit, emballage, livraison',
      voice: 'Sympathique, rapide et convaincant',
      cta: 'Commandez avant rupture de stock',
    },
  },

  realestate: {
    ar: {
      topic: 'خمسة أسئلة اسألها قبل شراء شقتك الأولى',
      notes: 'وضّح التكاليف الخفية وخيارات التمويل المتوافقة مع الشريعة',
      campaign: 'إطلاق مشروع الواحة السكني',
      objective: 'الحصول على 150 طلب معاينة خلال الشهر الأول من الإطلاق',
      tags: 'شقة، إطلالة، غرفة معيشة',
      voice: 'موثوق وهادئ وخبير — يساعدك على قرار مدروس',
      cta: 'احجز موعد المعاينة',
    },
    en: {
      topic: '5 questions to ask before buying your first condo',
      notes: 'Explain hidden costs and Islamic financing options',
      campaign: 'Riverside residences launch',
      objective: 'Secure 150 viewing requests in the first launch month',
      tags: 'condo, view, living room',
      voice: 'Trustworthy, calm and expert — for well-informed decisions',
      cta: 'Book a viewing',
    },
    ms: {
      topic: '5 soalan sebelum membeli rumah pertama anda',
      notes: 'Terangkan kos tersembunyi dan pilihan pembiayaan Islam',
      campaign: 'Pelancaran Residensi Seri Bayu',
      objective: 'Dapatkan 150 permintaan lawatan dalam bulan pertama',
      tags: 'kondominium, pemandangan, ruang tamu',
      voice: 'Dipercayai, tenang dan pakar — bantu keputusan yang bijak',
      cta: 'Tempah lawatan rumah contoh',
    },
    fr: {
      topic: '5 questions avant d’acheter votre premier appartement',
      notes: 'Détailler les frais cachés et les options de financement',
      campaign: 'Lancement des Jardins du Lac',
      objective: 'Obtenir 150 demandes de visite le premier mois',
      tags: 'appartement, vue, salon',
      voice: 'Fiable, posé et expert — pour décider en confiance',
      cta: 'Planifiez une visite',
    },
  },

  fashion: {
    ar: {
      topic: 'ثلاث إطلالات محتشمة لعيد الفطر',
      notes: 'نسّق القطع مع الإكسسوارات واذكر الخامات المناسبة للطقس الحار',
      campaign: 'مجموعة العيد 2027',
      objective: 'بيع 1000 قطعة من مجموعة العيد خلال أسبوعين',
      tags: 'عباية، عارضة، استوديو',
      voice: 'أنيق وواثق وعصري — بلمسة شخصية',
      cta: 'اكتشفي المجموعة الآن',
    },
    en: {
      topic: '3 modest outfits for Eid',
      notes: 'Pair pieces with accessories and note breathable fabrics',
      campaign: 'Eid collection 2027',
      objective: 'Sell 1,000 pieces from the Eid collection in two weeks',
      tags: 'abaya, model, studio',
      voice: 'Elegant, confident and modern — with a personal touch',
      cta: 'Shop the collection',
    },
    ms: {
      topic: '3 gaya baju kurung moden untuk Hari Raya',
      notes: 'Padankan dengan aksesori dan sebut fabrik yang selesa',
      campaign: 'Koleksi Raya 2027',
      objective: 'Jual 1,000 helai koleksi Raya dalam dua minggu',
      tags: 'baju kurung, model, studio',
      voice: 'Anggun, yakin dan moden — dengan sentuhan peribadi',
      cta: 'Lihat koleksi penuh',
    },
    fr: {
      topic: '3 tenues élégantes pour l’Aïd',
      notes: 'Associer chaque pièce à des accessoires et des tissus légers',
      campaign: 'Collection Aïd 2027',
      objective: 'Vendre 1 000 pièces de la collection en deux semaines',
      tags: 'abaya, mannequin, studio',
      voice: 'Élégant, assuré et moderne — avec une touche personnelle',
      cta: 'Découvrez la collection',
    },
  },

  health: {
    ar: {
      topic: 'علامات مبكرة لارتفاع السكر لا تتجاهلها',
      notes: 'استخدم لغة بسيطة وانصح بمراجعة الطبيب دون تخويف',
      campaign: 'شهر التوعية بالسكري',
      objective: 'حجز 300 فحص سكر مجاني خلال نوفمبر',
      tags: 'طبيب، عيادة، فحص',
      voice: 'مطمئن وموثوق وواضح — يضع صحتك أولًا',
      cta: 'احجز فحصك المجاني',
    },
    en: {
      topic: 'Early signs of high blood sugar you shouldn’t ignore',
      notes: 'Keep it simple and advise seeing a doctor without alarming',
      campaign: 'Diabetes awareness month',
      objective: 'Book 300 free blood sugar screenings in November',
      tags: 'doctor, clinic, check-up',
      voice: 'Reassuring, credible and clear — your health comes first',
      cta: 'Book your free screening',
    },
    ms: {
      topic: 'Tanda awal gula darah tinggi yang jangan diabaikan',
      notes: 'Guna bahasa mudah dan galakkan berjumpa doktor tanpa menakutkan',
      campaign: 'Bulan kesedaran diabetes',
      objective: 'Tempahan 300 saringan gula darah percuma pada November',
      tags: 'doktor, klinik, pemeriksaan',
      voice: 'Menenangkan, dipercayai dan jelas — kesihatan anda diutamakan',
      cta: 'Tempah saringan percuma',
    },
    fr: {
      topic: 'Diabète : les signes précoces à ne pas ignorer',
      notes: 'Rester simple et conseiller de consulter sans inquiéter',
      campaign: 'Mois de sensibilisation au diabète',
      objective: 'Réaliser 300 dépistages gratuits en novembre',
      tags: 'médecin, clinique, dépistage',
      voice: 'Rassurant, crédible et clair — votre santé d’abord',
      cta: 'Prenez rendez-vous',
    },
  },

  beauty: {
    ar: {
      topic: 'روتين بسيط للعناية بالبشرة في الطقس الرطب',
      notes: 'اذكر خطوات الصباح والمساء والمكونات المناسبة للبشرة الدهنية',
      campaign: 'إطلالة العروس 2027',
      objective: 'زيادة حجوزات جلسات العناية بالبشرة بنسبة 25٪',
      tags: 'عناية بالبشرة، صالون، منتجات',
      voice: 'لطيف وواثق وراقٍ — يجعلك تشعرين بالاهتمام',
      cta: 'احجزي جلستك اليوم',
    },
    en: {
      topic: 'A simple skincare routine for humid weather',
      notes: 'Cover morning and night steps and ingredients for oily skin',
      campaign: 'Bridal glow 2027',
      objective: 'Increase facial treatment bookings by 25%',
      tags: 'skincare, salon, products',
      voice: 'Gentle, confident and refined — you feel cared for',
      cta: 'Book your session today',
    },
    ms: {
      topic: 'Rutin penjagaan kulit ringkas untuk cuaca lembap',
      notes: 'Sebut langkah pagi dan malam serta bahan untuk kulit berminyak',
      campaign: 'Seri pengantin 2027',
      objective: 'Tingkatkan tempahan rawatan wajah sebanyak 25%',
      tags: 'penjagaan kulit, salun, produk',
      voice: 'Lembut, yakin dan elegan — anda rasa dihargai',
      cta: 'Tempah sesi anda hari ini',
    },
    fr: {
      topic: 'Une routine de soin simple pour les climats humides',
      notes: 'Détailler matin et soir et les actifs pour peau grasse',
      campaign: 'Éclat de la mariée 2027',
      objective: 'Augmenter de 25 % les réservations de soins du visage',
      tags: 'soin, institut, produits',
      voice: 'Doux, assuré et raffiné — on prend soin de vous',
      cta: 'Réservez votre soin',
    },
  },

  automotive: {
    ar: {
      topic: 'خمس علامات تخبرك أن سيارتك تحتاج صيانة الآن',
      notes: 'اذكر أصوات الفرامل ولمبات التحذير وتكلفة التأخير',
      campaign: 'فحص ما قبل السفر في العيد',
      objective: 'حجز 400 موعد صيانة قبل عطلة العيد',
      tags: 'ورشة، فني، سيارة',
      voice: 'خبير وصريح وموثوق — بلا مصطلحات معقدة',
      cta: 'احجز موعد الصيانة',
    },
    en: {
      topic: '5 signs your car needs a service now',
      notes: 'Cover brake noises, warning lights and the cost of waiting',
      campaign: 'Pre-holiday car check',
      objective: 'Book 400 service appointments before the holidays',
      tags: 'workshop, mechanic, car',
      voice: 'Expert, straight-talking and reliable — no jargon',
      cta: 'Book a service slot',
    },
    ms: {
      topic: '5 tanda kereta anda perlu diservis segera',
      notes: 'Sebut bunyi brek, lampu amaran dan kos jika ditangguhkan',
      campaign: 'Pemeriksaan sebelum balik kampung',
      objective: 'Tempahan 400 servis sebelum cuti Hari Raya',
      tags: 'bengkel, mekanik, kereta',
      voice: 'Pakar, berterus terang dan boleh diharap — tanpa jargon',
      cta: 'Tempah slot servis',
    },
    fr: {
      topic: '5 signes que votre voiture doit passer à l’entretien',
      notes: 'Parler des bruits de freins, des voyants et du coût d’attendre',
      campaign: 'Contrôle avant les vacances',
      objective: 'Réserver 400 rendez-vous d’entretien avant les congés',
      tags: 'garage, mécanicien, voiture',
      voice: 'Expert, franc et fiable — sans jargon',
      cta: 'Prenez rendez-vous au garage',
    },
  },

  events: {
    ar: {
      topic: 'كواليس تجهيز مؤتمر لـ 800 مشارك في كوالالمبور',
      notes: 'أظهر عمل الفريق والتفاصيل الصغيرة التي تصنع الفرق',
      campaign: 'قمة الأعمال 2027',
      objective: 'بيع 600 تذكرة قبل نهاية فترة السعر المبكر',
      tags: 'مسرح، جمهور، قاعة مؤتمرات',
      voice: 'حماسي ومنظم واحترافي — يعدك بتجربة لا تُنسى',
      cta: 'احجز تذكرتك الآن',
    },
    en: {
      topic: 'Behind the scenes of an 800-guest summit in KL',
      notes: 'Show the crew at work and the small details that matter',
      campaign: 'Business summit 2027',
      objective: 'Sell 600 tickets before early-bird pricing ends',
      tags: 'stage, audience, ballroom',
      voice: 'Energetic, organised and professional — unforgettable',
      cta: 'Get your ticket now',
    },
    ms: {
      topic: 'Di sebalik tabir majlis perkahwinan 500 tetamu',
      notes: 'Tunjukkan kerja pasukan dan butiran kecil yang membezakan',
      campaign: 'Pakej perkahwinan 2027',
      objective: 'Tempahan 20 majlis perkahwinan bagi musim cuti sekolah',
      tags: 'pelamin, tetamu, dewan',
      voice: 'Bersemangat, tersusun dan profesional',
      cta: 'Tempah tarikh majlis anda',
    },
    fr: {
      topic: 'Les coulisses d’un sommet de 800 invités',
      notes: 'Montrer l’équipe en action et les détails qui font la différence',
      campaign: 'Sommet des affaires 2027',
      objective: 'Vendre 600 billets avant la fin du tarif préférentiel',
      tags: 'scène, public, salle de conférence',
      voice: 'Dynamique, organisé et professionnel — mémorable',
      cta: 'Réservez votre billet',
    },
  },

  government: {
    ar: {
      topic: 'إطلاق الخدمة الإلكترونية الجديدة لتجديد التراخيص',
      notes: 'وضّح من يحق له الاستفادة والخطوات والمستندات المطلوبة وموعد التطبيق',
      campaign: 'حملة التحول الرقمي للخدمات',
      objective: 'رفع استخدام الخدمات الإلكترونية إلى 70% خلال العام',
      tags: 'مبنى حكومي، خدمة، مواطن',
      voice: 'رسمي وواضح ودقيق — يخدم الجمهور بثقة',
      cta: 'تفضّلوا بزيارة البوابة الرسمية',
    },
    en: {
      topic: 'Launch of the new online licence renewal service',
      notes: 'Explain who is eligible, the steps, required documents and start date',
      campaign: 'Digital services campaign',
      objective: 'Raise online service usage to 70% this year',
      tags: 'government building, service, citizen',
      voice: 'Formal, clear and precise — serving the public with confidence',
      cta: 'Visit the official portal',
    },
    ms: {
      topic: 'Pelancaran perkhidmatan dalam talian baharu untuk pembaharuan lesen',
      notes: 'Terangkan siapa yang layak, langkah, dokumen diperlukan dan tarikh mula',
      campaign: 'Kempen pendigitalan perkhidmatan',
      objective: 'Tingkatkan penggunaan perkhidmatan dalam talian kepada 70% tahun ini',
      tags: 'bangunan kerajaan, perkhidmatan, rakyat',
      voice: 'Rasmi, jelas dan tepat — berkhidmat untuk rakyat',
      cta: 'Layari portal rasmi',
    },
    fr: {
      topic: 'Lancement du nouveau service en ligne de renouvellement des permis',
      notes: 'Préciser les bénéficiaires, les étapes, les pièces requises et la date d’entrée en vigueur',
      campaign: 'Campagne de services numériques',
      objective: 'Porter l’usage des services en ligne à 70 % cette année',
      tags: 'bâtiment public, service, citoyen',
      voice: 'Officiel, clair et précis — au service du public',
      cta: 'Consultez le portail officiel',
    },
  },

  car_rental: {
    ar: {
      topic: 'أفضل 5 رحلات برية بسيارة مستأجرة من كوالالمبور',
      notes: 'اذكر المسافات ونوع السيارة المناسب لكل رحلة وأسعار الإيجار اليومي',
      campaign: 'عروض إيجار العطلة المدرسية',
      objective: 'حجز 250 سيارة خلال العطلة المدرسية',
      tags: 'سيارة، طريق، مطار',
      voice: 'ودود وعملي وسريع — سيارتك جاهزة متى احتجتها',
      cta: 'احجز سيارتك الآن',
    },
    en: {
      topic: '5 best road trips from Kuala Lumpur in a rental car',
      notes: 'Mention distances, the right car for each trip and daily rental prices',
      campaign: 'School holiday rental deals',
      objective: 'Book 250 rentals during the school holidays',
      tags: 'car, road, airport',
      voice: 'Friendly, practical and fast — your car is ready when you are',
      cta: 'Book your car now',
    },
    ms: {
      topic: '5 perjalanan darat terbaik dari Kuala Lumpur dengan kereta sewa',
      notes: 'Nyatakan jarak, kereta sesuai untuk setiap perjalanan dan harga sewa harian',
      campaign: 'Tawaran sewa cuti sekolah',
      objective: 'Tempahan 250 kereta sepanjang cuti sekolah',
      tags: 'kereta, jalan raya, lapangan terbang',
      voice: 'Mesra, praktikal dan pantas — kereta anda sedia bila-bila masa',
      cta: 'Tempah kereta anda sekarang',
    },
    fr: {
      topic: '5 road trips depuis Kuala Lumpur en voiture de location',
      notes: 'Indiquer les distances, la voiture adaptée et les tarifs journaliers',
      campaign: 'Offres location vacances scolaires',
      objective: 'Réserver 250 locations pendant les vacances scolaires',
      tags: 'voiture, route, aéroport',
      voice: 'Sympathique, pratique et rapide — votre voiture vous attend',
      cta: 'Réservez votre voiture',
    },
  },

  general: {
    ar: {
      topic: 'ثلاثة أسباب تجعل عملاءنا يعودون إلينا',
      notes: 'اذكر رأي عميل حقيقي وميزة واحدة تميزنا عن المنافسين',
      campaign: 'حملة نهاية العام 2027',
      objective: 'زيادة الاستفسارات عبر واتساب بنسبة 25٪ خلال الربع',
      tags: 'فريق العمل، مكتب، عملاء',
      voice: 'ودود ومهني وواضح — قريب من الناس',
      cta: 'تواصل معنا اليوم',
    },
    en: {
      topic: '3 reasons our customers keep coming back',
      notes: 'Include a real customer quote and one thing that sets us apart',
      campaign: 'Year-end campaign 2027',
      objective: 'Grow WhatsApp enquiries by 25% this quarter',
      tags: 'team, office, customers',
      voice: 'Friendly, professional and clear — close to people',
      cta: 'Get in touch today',
    },
    ms: {
      topic: '3 sebab pelanggan terus kembali kepada kami',
      notes: 'Masukkan testimoni pelanggan dan satu kelebihan utama kami',
      campaign: 'Kempen hujung tahun 2027',
      objective: 'Tingkatkan pertanyaan WhatsApp sebanyak 25% suku ini',
      tags: 'pasukan, pejabat, pelanggan',
      voice: 'Mesra, profesional dan jelas — dekat dengan pelanggan',
      cta: 'Hubungi kami hari ini',
    },
    fr: {
      topic: '3 raisons pour lesquelles nos clients reviennent',
      notes: 'Inclure un témoignage client et ce qui nous distingue',
      campaign: 'Campagne de fin d’année 2027',
      objective: 'Augmenter de 25 % les demandes WhatsApp ce trimestre',
      tags: 'équipe, bureau, clients',
      voice: 'Sympathique, professionnel et clair — proche des gens',
      cta: 'Contactez-nous dès aujourd’hui',
    },
  },
};

export function example(industry, lang, field) {
  return (
    EXAMPLES[industry]?.[lang]?.[field] ??
    EXAMPLES.general[lang]?.[field] ??
    EXAMPLES.general.en[field] ??
    ''
  );
}
